version: '3.9'
services:
  db:
    container_name: db
    image: postgres
    restart: always
    expose:
      - 5432
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:      
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -t 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    networks:
      - dev
  api:
    container_name: api
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - 4005:4005
    depends_on:
      - db
    networks:
      - dev

networks:
  dev:
    driver: bridge